### ISSUE TITLE
Max retries support?

### ISSUE THREAD

**Issue by tj** [FoundationDB/fdb-go#15]
I'd completely understand retrying some configurable number of times but indefinitely makes it appear like a transaction is much slower than it is, because it's just sitting there thrashing over and over. This fooled me locally, I could see it being an even bigger pain in production since most metrics are delta based.

I know it's this way by-design but is there a way to configure the amount of retries? Or would anyone be ok with supporting it?

**Comment by ipeters** [comment]
TJ,

It is, as you note, a design choice to do the most conservative thing by default (an application has no way to judge whether a failing transaction will succeed in the future). It's worth noting that it shouldn't be thrashing too hard, as the standard retry behavior does have an exponential backoff.

Nevertheless, you can call [`SetRetryLimit`](http://godoc.org/github.com/FoundationDB/fdb-go/fdb#TransactionOptions.SetRetryLimit) on a `TransactionOptions` object (`Transaction.Options().SetRetryLimit`) to configure the maximum number of retry attempts before returning an error. You may also want to look at the related `SetMaxRetryDelay` and `SetTimeout` for other ways to influence the retry loop.

**Comment by tj** [comment]
Any way to specify it application-wide?

**Comment by ipeters** [comment]
Not at the moment (although I believe at least the .NET bindings do have this facility).

It wouldn't be particularly difficult to add the ability to configure default transaction options that would apply to any transaction implicitly created by `Database.Transact` (or `ReadTransact`). I would be much more hesitant to try to apply default options to the transaction returned by `Database.CreateTransaction`, not least because transaction options are reset after calls to `OnError` and `Reset`.

In the meantime, though, it would have to be set inside of every function passed to `Database.Transact`, e.g.

```
db.Transact(func (tr fdb.Transaction) (interface{}, error) {
  tr.Options().SetRetryLimit(3)
  ...
})
```

In the meantime, if you have the same options you want applied every time, you could write a wrapper to reuse.

**Comment by tj** [comment]
Yeah true not a big deal, I was mostly just surprised that it was looping over and over. Whatever the default is seems a little scary, but now I know to watch out for that haha. cheers

**Comment by ipeters** [comment]
I think all of us internally have been bitten by it as well! It's not the expected development experience for a lot of people. The alternative, where a transient availability failure of a database in production could lead to an error cascade resulting in a permanent availability loss at the application tier (until things were restarted) seemed like it was worse.

There was discussion at one point a while back of a "development" mode that would tweak defaults when not running in production, but that obviously has not happened.
